// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://kkmpkbhszkmpkurwtenn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtrbXBrYmhzemttcGt1cnd0ZW5uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MDE2MjMsImV4cCI6MjA2MDI3NzYyM30.GIlvXcVEQyzvuZyP_ozIA3H6_cBOm0MkZdPfPBtEybo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);